services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: repas
      POSTGRES_PASSWORD: repas
      POSTGRES_DB: repas
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: